/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import java.sql.*;
import javax.swing.*;
import java.text.SimpleDateFormat;

/**BookRide h = new BookRide(username);
                h.setVisible(true);
                this.dispose();
 *
 * @author vuk ksc
 */
public class RideDetails extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String carCategory, carLicense = null, driverNo = null, username, booking_id = null, pickupDate = null;

    double triplength;

    /**
     * Creates new form LOgout
     *
     * @param username
     */
    public RideDetails(String username, String carCategory) {
        this.carCategory = carCategory;
        this.username = username;
        initComponents();
        fillTextfields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        source = new java.awt.TextField();
        destination = new java.awt.TextField();
        txtdate = new java.awt.TextField();
        noSeats = new java.awt.TextField();
        features = new java.awt.TextField();
        jLabel27 = new javax.swing.JLabel();
        carCategry = new java.awt.TextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        carModel = new java.awt.TextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        driverName = new java.awt.TextField();
        driverContact = new java.awt.TextField();
        jLabel34 = new javax.swing.JLabel();
        btnProceed = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtdistance = new java.awt.TextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtprice = new java.awt.TextField();
        txtrate = new java.awt.TextField();
        txttime = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(java.awt.Color.orange);
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 800));

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel17.setText("Source :");
        jLabel17.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel20.setForeground(java.awt.Color.black);
        jLabel20.setText("YOUR RIDE DETAILS :");

        jLabel22.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel22.setText("No. of Seats :");

        jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel23.setText("Pick-up Date  :");

        jLabel25.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel25.setText("Pick-up Time :");

        jLabel26.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel26.setText("Destination :");

        jLabel24.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel24.setText("Features :");

        source.setBackground(java.awt.Color.orange);
        source.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        source.setText("textField1");
        source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceActionPerformed(evt);
            }
        });

        destination.setBackground(java.awt.Color.orange);
        destination.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        destination.setText("textField1");

        txtdate.setBackground(java.awt.Color.orange);
        txtdate.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        txtdate.setText("textField1");

        noSeats.setBackground(java.awt.Color.orange);
        noSeats.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        noSeats.setText("textField1");

        features.setBackground(java.awt.Color.orange);
        features.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        features.setText("textField1");

        jLabel27.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel27.setText("Car Category :");

        carCategry.setBackground(java.awt.Color.orange);
        carCategry.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        carCategry.setText("textField1");

        jLabel28.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel28.setText("Car Details :");

        jLabel29.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel29.setText("Car Model allotted :");

        carModel.setBackground(java.awt.Color.orange);
        carModel.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        carModel.setText("textField1");

        jLabel30.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel30.setText("Driver Details :");

        jLabel31.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel31.setText("Name :");

        jLabel32.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel32.setText("Contact No. :");

        driverName.setBackground(java.awt.Color.orange);
        driverName.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        driverName.setText("textField1");

        driverContact.setBackground(java.awt.Color.orange);
        driverContact.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        driverContact.setText("textField1");

        jLabel34.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        btnProceed.setBackground(java.awt.Color.black);
        btnProceed.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnProceed.setForeground(java.awt.Color.orange);
        btnProceed.setText("Proceed to Payment");
        btnProceed.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        btnBack.setBackground(java.awt.Color.black);
        btnBack.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnBack.setForeground(java.awt.Color.orange);
        btnBack.setText("Back to Home");
        btnBack.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtdistance.setBackground(java.awt.Color.orange);
        txtdistance.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        txtdistance.setText("textField1");

        jLabel33.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel33.setText("Distance Covered :");

        jLabel35.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel35.setText("Rate (Rs. / km) :");

        jLabel36.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel36.setText("Total Price :");

        txtprice.setBackground(java.awt.Color.orange);
        txtprice.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        txtprice.setText("textField1");

        txtrate.setBackground(java.awt.Color.orange);
        txtrate.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        txtrate.setText("textField1");

        txttime.setBackground(java.awt.Color.orange);
        txttime.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        txttime.setText("textField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(features, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carModel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carCategry, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(source, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(driverName, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(223, 223, 223))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtdistance, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtrate, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(driverContact, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(329, 329, 329))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(source, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(features, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carCategry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(driverName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(driverContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBackground(java.awt.Color.black);

        jLabel1.setBackground(java.awt.Color.lightGray);
        jLabel1.setFont(new java.awt.Font("URW Gothic L", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.orange);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book A Ride!");

        btnHome.setBackground(java.awt.Color.black);
        btnHome.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnHome.setForeground(java.awt.Color.orange);
        btnHome.setText("Home");
        btnHome.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnHome.setBorderPainted(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnHistory.setBackground(java.awt.Color.black);
        btnHistory.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnHistory.setForeground(java.awt.Color.orange);
        btnHistory.setText("Ride History");
        btnHistory.setBorder(new javax.swing.border.MatteBorder(null));
        btnHistory.setBorderPainted(false);
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        btnProfile.setBackground(java.awt.Color.black);
        btnProfile.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnProfile.setForeground(java.awt.Color.orange);
        btnProfile.setText("Profile");
        btnProfile.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnProfile.setBorderPainted(false);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnLogout.setBackground(java.awt.Color.black);
        btnLogout.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnLogout.setForeground(java.awt.Color.orange);
        btnLogout.setText("Logout");
        btnLogout.setBorder(new javax.swing.border.MatteBorder(null));
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
            .addComponent(btnProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceActionPerformed

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        // TODO add your handling code here:
        conn = MySqlConnect.ConnectDB();
        try {
            String sql = "select * from booking order by booking_id desc limit 1";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                this.booking_id = rs.getString("booking_id");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        String Sql2 = "insert into transaction values(null, ?, null, ?)";
        try {
            pst = conn.prepareStatement(Sql2);
            pst.setString(1, this.booking_id);
            pst.setDouble(2, this.triplength);
            int i = pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        String Sql3 = "update booking set driver_login_id = ? where booking_id = ?";
        try {
            pst = conn.prepareStatement(Sql3);
            pst.setString(2, this.booking_id);
            pst.setString(1, this.driverNo);
            int i = pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        String Sql1 = "insert into availability values (?, ?, ?, ?)";
        try {
            pst = conn.prepareStatement(Sql1);

            pst.setString(1, this.driverNo);
            pst.setString(2, this.pickupDate);
            pst.setString(3, this.carLicense);
            pst.setString(4, this.booking_id);
            int i = pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        PaymentMethod h = new PaymentMethod(username);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProceedActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        conn = MySqlConnect.ConnectDB();
        String Sql1 = "delete from booking order by booking_id desc limit 1";
        try {
            pst = conn.prepareStatement(Sql1);
            int i = pst.executeUpdate();
            JOptionPane.showConfirmDialog(null, "Confirm leaving page?");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        this.dispose();
        new BookRide(this.username).setVisible(true);


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        conn = MySqlConnect.ConnectDB();
        String Sql1 = "delete from booking order by booking_id desc limit 1";
        try {
            pst = conn.prepareStatement(Sql1);
            int i = pst.executeUpdate();
            JOptionPane.showConfirmDialog(null, "Confirm leaving page?");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        HomeCustomer h = new HomeCustomer(username);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        conn = MySqlConnect.ConnectDB();
        String Sql1 = "delete from booking order by booking_id desc limit 1";
        try {
            pst = conn.prepareStatement(Sql1);
            int i = pst.executeUpdate();
            JOptionPane.showConfirmDialog(null, "Confirm leaving page?");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            String sql = "select * from customer where login_id = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, this.username);
            rs = pst.executeQuery();

            if (rs.next()) {
                RideHistory h = new RideHistory(username);
                h.setVisible(true);
                this.dispose();
            } else {
                DriverHistory h = new DriverHistory(username);
                h.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        conn = MySqlConnect.ConnectDB();
        String Sql1 = "delete from booking order by booking_id desc limit 1";
        try {
            pst = conn.prepareStatement(Sql1);
            int i = pst.executeUpdate();
            JOptionPane.showConfirmDialog(null, "Confirm leaving page?");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            String sql = "select * from customer where login_id = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, this.username);
            rs = pst.executeQuery();

            if (rs.next()) {
                CustomerProfile h = new CustomerProfile(username);
                h.setVisible(true);
                this.dispose();
            } else {
                EmployeeProfile h = new EmployeeProfile(username);
                h.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        conn = MySqlConnect.ConnectDB();
        String Sql1 = "delete from booking order by booking_id desc limit 1";
        try {
            pst = conn.prepareStatement(Sql1);
            int i = pst.executeUpdate();
            JOptionPane.showConfirmDialog(null, "Confirm logout?");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        LoginPage h = new LoginPage();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    public void fillTextfields() {
        conn = MySqlConnect.ConnectDB();
        String Source = null, Destination = null, Modelno = null;
        double sLatitude = 0, sLongitude = 0, dLatitude = 0, dLongitude = 0, Distance = 0, price, rate = 0;

        try {
            String sql = "select * from booking order by booking_id desc limit 1";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {

                source.setText(rs.getString("source_name"));
                Source = rs.getString("source_name");
                destination.setText(rs.getString("destination_name"));
                Destination = rs.getString("destination_name");
                pickupDate = rs.getString("pickup_date");
                txtdate.setText(rs.getString("pickup_date"));
                txttime.setText(rs.getString("pickup_time"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            String sql = "select * from car where model_no in (select model_no from car_model where car_category = ?) && license_no not in (select car_no from availability where pickup_date = ?) && depot_id in (select depot_id from locations_available where location = ?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, this.carCategory);
            pst.setString(2, this.pickupDate);
            pst.setString(3, Source);
            rs = pst.executeQuery();
            if (rs.next()) {
                this.carLicense = rs.getString("license_no");
                try {
                    String sql5 = "select distinct * from driver where login_id not in (select login_id from availability where pickup_date = ?) && depot_id in (select depot_id from locations_available where location = ?)";
                    pst = conn.prepareStatement(sql5);
                    pst.setString(2, Source);
                    pst.setString(1, this.pickupDate);
                    rs = pst.executeQuery();

                    if (rs.next()) {
                        this.driverNo = rs.getString("login_id");
                    } else {
                        JOptionPane.showMessageDialog(null, "No Driver Available!");
                        BookRide h = new BookRide(username);
                        h.setVisible(true);
                        this.dispose();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                try {
                    String sql5 = "select distinct * from car_rate where car_category = ?";
                    pst = conn.prepareStatement(sql5);
                    pst.setString(1, this.carCategory);
                    rs = pst.executeQuery();

                    if (rs.next()) {
                        carCategry.setText(this.carCategory);
                        features.setText(rs.getString("features"));
                        noSeats.setText(rs.getString("no_of_seats"));
                        rate = rs.getDouble("rate");
                        txtrate.setText(String.valueOf(rate));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                try {
                    String sql4 = "select * from car_model where model_no in (select model_no from car where license_no = ?)";
                    pst = conn.prepareStatement(sql4);
                    pst.setString(1, this.carLicense);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        carModel.setText(rs.getString("model_name"));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                try {
                    String sql3 = "select distinct * from employee where login_id = ?";
                    pst = conn.prepareStatement(sql3);
                    pst.setString(1, this.driverNo);
                    rs = pst.executeQuery();

                    if (rs.next()) {
                        driverContact.setText(rs.getString("mobile_no"));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                try {
                    String sql2 = "select distinct * from name where login_id = ?";
                    pst = conn.prepareStatement(sql2);
                    pst.setString(1, this.driverNo);
                    rs = pst.executeQuery();

                    if (rs.next()) {
                        driverName.setText(rs.getString("first_name") + " " + rs.getString("last_name"));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                try {
                    String sql1 = "select distinct * from locations_available where location = ?";
                    pst = conn.prepareStatement(sql1);
                    pst.setString(1, Source);
                    rs = pst.executeQuery();

                    if (rs.next()) {
                        sLatitude = rs.getDouble("latitude");
                        sLongitude = rs.getDouble("longitude");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                try {
                    String sql6 = "select distinct * from locations_available where location = ?";
                    pst = conn.prepareStatement(sql6);
                    pst.setString(1, Destination);
                    rs = pst.executeQuery();

                    if (rs.next()) {
                        dLatitude = rs.getDouble("latitude");
                        dLongitude = rs.getDouble("longitude");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                Distance = distance(sLatitude, dLatitude, sLongitude, dLongitude);
                price = 1.5 * rate * Distance;
                Distance = limitPrecision(String.valueOf(Distance), 2);
                this.triplength = Distance;
                price = limitPrecision(String.valueOf(price), 2);
                txtdistance.setText(String.valueOf(Distance));
                txtprice.setText(String.valueOf(price));

            } else {

                JOptionPane.showMessageDialog(null, "No Car Available!");
                BookRide h = new BookRide(username);
                h.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public static double distance(double lat1, double lat2, double lon1,
            double lon2) {

        final int R = 6371; // Radius of the earth

        double latDistance = Math.toRadians(lat2 - lat1);
        double lonDistance = Math.toRadians(lon2 - lon1);
        double a = Math.sin(latDistance / 2) * Math.sin(latDistance / 2)
                + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2))
                * Math.sin(lonDistance / 2) * Math.sin(lonDistance / 2);
        double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
        double distance = R * c; // answer is in kilometers
        return distance;
    }

    public double limitPrecision(String dblAsString, int maxDigitsAfterDecimal) {
        int multiplier = (int) Math.pow(10, maxDigitsAfterDecimal);
        double truncated = (double) ((long) ((Double.parseDouble(dblAsString)) * multiplier)) / multiplier;
        return truncated;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RideDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RideDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RideDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RideDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RideDetails("admin ", "A").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProceed;
    private javax.swing.JButton btnProfile;
    private java.awt.TextField carCategry;
    private java.awt.TextField carModel;
    private java.awt.TextField destination;
    private java.awt.TextField driverContact;
    private java.awt.TextField driverName;
    private java.awt.TextField features;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.TextField noSeats;
    private java.awt.TextField source;
    private java.awt.TextField txtdate;
    private java.awt.TextField txtdistance;
    private java.awt.TextField txtprice;
    private java.awt.TextField txtrate;
    private java.awt.TextField txttime;
    // End of variables declaration//GEN-END:variables
}
